### ISSUE TITLE
Crossterm exiting artifacts/bug

### ISSUE THREAD

**Issue by scOwez** [gyscos/cursive#405]
# Problem description

Getting some unexpected behavior when exiting with `crossterm-backend` as the back-end used for cursive.

When exiting a cursive-built application, the terminal continues to display mouse metadata (the `10M32;103;10M32`-type codes) and the terminal cursor vanishes. Here is an example:

![image](https://user-images.githubusercontent.com/30081702/68164671-5f702980-ff55-11e9-8dc3-86b48be1d9f4.png)

I have seen similar problems happening with [`micro`](https://github.com/zyedidia/micro) but as for relevant backends, this is only happening with crossterm.

# Environment

* Operating system: Ubuntu 18.04
* Backend used: `crossterm-backend`
* Current locale: `en_GB.UTF-8`
* Cursive version: `0.13`

Tested with default `bash` and `zsh` shells on the integrated VSCode emulator, Tilix and the default GNOME emulator.

**Comment by gyscos** [comment]
Thanks for the report!

Could you try the latest git version? It might have been fixed in https://github.com/gyscos/cursive/pull/400.

You can update your `Cargo.toml` to use the latest git:

```toml
[dependencies.cursive]
git = "https://github.com/gyscos/cursive"
default-features = false
features = ["crossterm-backend"]
```
