### ISSUE TITLE
Question: Eliminating dependency on ncurses

### ISSUE THREAD

**Issue by ahbnr** [gyscos/cursive#430]
Hi!

I'm trying to eliminate the ncurses dependency from my application, so that users do not need to install it.

I configured my project to use the termion backend like this:
```toml
[dependencies.cursive]
version = "0.14.0"
default-features = false
features = ["toml", "termion-backend"]
```
(I also changed my code to use [cursive_buffered_backend](https://github.com/agavrilov/cursive_buffered_backend) to get rid of flickering, see also https://github.com/gyscos/cursive/issues/142#issuecomment-432837853)

However,

```sh
$ ldd target/debug/myapp | grep ncurses
libncursesw.so.6 => /usr/lib/libncursesw.so.6 (...)
```

reveals that my application still dynamically links to ncurses.

Is it possible to configure the project so that it does not link to ncurses at all?

Thank you very much!

# Environment

* Operating system: Arch Linux
* Backend used: termion
  * installed ncurses version: 6.2
* Current locale: en_US.UTF-8
* Cursive version: 0.14.0
