### ISSUE TITLE
Load layout from configuration file

### ISSUE THREAD

**Issue by Gyscos** [Gyscos/Cursive#5]
It may be easier to define some complex layouts in external files rather than build it manually in the source code.

Would need to define a layout representation (xml? json?)...

**Comment by matthiasbeyer** [comment]
IMHO, XML has some nice ways of describing meta-information you may have for a view, so I guess it would be a good fit. I consider XML ugly, though I have to admit that item attributes are a nice thing that JSON or YAML do not have.

I like TOML, though I'd agree taht it is not _that_ appropriate for the problem.

**Comment by gyscos** [comment]
I've been eyeing yaml lately, as a more readable JSON. Here is an example file describing a basic application:

```yaml
definitions:
  - first:
      Dialog:
          child:
              TextView:
                  text: >
                      This is a long text!
                      A little too long to
                      fit on one line.
          buttons:
              - label: Ok
                callback: $next
              - label: Ok
                callback: $quit
          with:
              - fixed_width: 8
  - next:
      Dialog:
          title: Congratulations!
          child:
              TextView:
                  text: Thank you for your time.
          buttons:
              - label: Quit
                callback: $quit
                       
layers:
  - $first
```

And the corresponding JSON:

```json
{
  "layers": [
    "$first"
  ],
  "definitions": [
    {
      "first": {
        "Dialog": {
          "buttons": [
            {
              "callback": "$next",
              "label": "Ok"
            },
            {
              "callback": "$quit",
              "label": "Ok"
            }
          ],
          "with": [
            {
              "fixed_width": 8
            }
          ],
          "child": {
            "TextView": {
              "text": "This is a long text! A little too long to fit on one line.\n"
            }
          }
        }
      }
    },
    {
      "next": {
        "Dialog": {
          "buttons": [
            {
              "callback": "$quit",
              "label": "Quit"
            }
          ],
          "title": "Congratulations!",
          "child": {
            "TextView": {
              "text": "Thank you for your time."
            }
          }
        }
      }
    }
  ]
}
```

The parser would take a map of callbacks, and the config file would reference those (`callback: $quit` for instance). Not sure yet how to handle different kinds of callbacks (like [`TextView::on_submit`]).

Here is the same example, written in a possible xml format:

```xml
<definitions>
    <Dialog name="first">
        <child>
            <TextView>
                <text>This is a long text! A little too long to fit on one line.</text>
            </TextView>
        </child>
        <buttons>
            <button callback="$next">Ok</button>
            <button callback="$quit">Cancel</button>
        </buttons>
        <with>
            <fixed_width>8</fixed_width>
        </with>
    </Dialog>
    <Dialog name="next">
        <title>Congratulations!</title>
        <child>
            <TextView>
                <text>Thank your for your time.</text>
            </TextView>
        </child>
        <buttons>
            <button callback="$quit">Quit</button>
        </buttons>
    </Dialog>
</definitions>

<layers>
    <layer>$first</layer>
</layers>
```

[`TextView::on_submit`]: http://gyscos.github.io/Cursive/cursive/views/struct.EditView.html#method.on_submit
