### ISSUE TITLE
Cursive_Table_View doesn't build with cursive

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#537]
This setup in Cargo.toml doesn't work, I'm getting error saying that probably two versions of cursive_core are used:

[dependencies]
cursive = {git="https://github.com/gyscos/cursive.git",branch="main"}
cursive_table_view = "*"

Best Regards

**Comment by gyscos** [comment]
Yeah it's not easy to combine git dependencies with dependencies from crates.io, since cargo isn't sure that they are compatible.

I _think_ if you give a version to cursive in addition to the `git` value, it _might_ help, but there's a chance you'll need to use the cursive from crates.io as well.

You _might_ be able to patch the dependencies (see the [documentation](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section)):

```toml
[dependencies]
cursive = "0.16"
cursive_table_view = "0.13"

[patch.crates-io]
cursive = {git="https://github.com/gyscos/cursive.git",branch="main"}
```

Haven't tested it though.
