### ISSUE TITLE
[Feature] Separating chrono into optional dependencies

### ISSUE THREAD

**Issue by cu233** [gyscos/cursive#612]
**Is your feature request related to a problem? Please describe.**

https://github.com/gyscos/cursive/issues/585

https://github.com/chronotope/chrono/issues/602

cursive-core depends on chrono, chrono depends on time(very very old version), it has a security problem.

**CVE-2020-26235**

We can use cargo audit to audit rust crates.

```shell
cargo install cargo-audit
cargo audit
```

**Describe the solution you'd like**

We can make this an optional feature rather than a mandatory one.

```toml
[features]
time_logger = ["chrono"]

[dependencies.chrono]
optional = true
version = "0.4.19"
```

**Describe alternatives you've considered**

Not using chrono.

**Additional context**
