### ISSUE TITLE
[Question] Readme example not working for me

### ISSUE THREAD

**Issue by ghlecl** [gyscos/cursive#648]
Sorry for such a basic question, but the example in the readme does not work for me.  Here is the content of my cargo.toml file:

```toml
[package]
name = "cursive_readme_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.cursive]
version = "~0.18"
default-features = false

[features]
crossterm-backend = ["cursive/crossterm-backend"]
```

In the main.rs file, I have literally copied the code from the readme example (the Hello Dialog example).  The application compiles, but I can't get it to run neither on Windows nor on macOs.

Maybe I am doing something wrong and there is something I never knew on how to start TUI applications.  The only other TUI application I have ever used (I think) is `ccmake` and all I had to do to use this application is start it in the command line, so I am naively just typing `./target/debug/cursive_readme_test` and nothing happens.   I have also tried starting it via cargo (as `cargo run`), but it won't work either.  No matter what I try, nothing happens.

If anyone could point me to the dumb thing I am forgetting, it would be greatly appreciated.  Again, sorry for such a basic question.

**Comment by gyscos** [comment]
Hi!
Your Cargo.toml defines a crossterm-backend feature that forwards it to cursive. It's exactly what you need to run on windows, but by default it doesn't seem to be enabled.

You turn it on using `cargo run --features crossterm-backend`. You can also turn it on by default with

```toml
[package]
name = "cursive_readme_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.cursive]
version = "~0.18"
default-features = false

[features]
default = ["crossterm-backend"]
crossterm-backend = ["cursive/crossterm-backend"]
```

Or simply always turn on this feature in cursive:

```toml
[package]
name = "cursive_readme_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.cursive]
version = "~0.18"
default-features = false
features = ["crossterm-backend"]
```

Either of these 3 solutions should get you running.
