### ISSUE TITLE
[BUG] Cursive window borders contain gaps when viewed in Windows Terminal

### ISSUE THREAD

**Issue by riverar** [gyscos/cursive#709]
## Describe the bug
When displaying the example window in the Terminal app on Windows 11 (using the default font of `Cascadia Mono`), window borders contain a gap near the top-left and top-right corners. Screenshots have been provided below.

(If you need access to a Windows environment, let me know.)

## Steps to reproduce

1. Compile crate using files below.
2. Launch Terminal app on Windows.
3. Execute `app.exe` and observe results. (Screenshot provided above.)

* Cargo.toml
  ```toml
  [package]
  name = "app"
  version = "0.0.0"
  edition = "2018"
  publish = false
  
  [dependencies.cursive]
  version = "0.20"
  default-features = false
  features = ["crossterm-backend"]
  ````

* main.rs
  ```rust
  use cursive::views::{Dialog, TextView};
  
  fn main() {
      // Creates the cursive root - required for every application.
      let mut siv = cursive::default();
  
      // Creates a dialog with a single "Quit" button
      siv.add_layer(Dialog::around(TextView::new("Hello Dialog!"))
                           .title("Cursive")
                           .button("Quit", |s| s.quit()));
  
      // Starts the event loop.
      siv.run();
  }
  ```

## Screenshots
* Figure 1 - Example window showing gaps (Cascadia font family, default)

  ![image](https://user-images.githubusercontent.com/475132/211430839-c34f78e0-a425-440b-8146-a7957ed3243a.png)

* Figure 2 - Attempt at reproducing the issue with a UTF-8 encoded text file containing drawing characters

  ![image](https://user-images.githubusercontent.com/475132/211431073-7615ac64-592c-41a6-b35e-07206c39cd60.png)

* Figure 3 - Example window without gaps (Consolas font face)

  ![image](https://user-images.githubusercontent.com/475132/211432097-3563ed13-cbe0-46fd-ba78-6105e7c5e763.png)

## Environment
* Tested on Windows 11 22000.739 (retail), 25272.1000 (insider)
* `crossterm` backend
* cursive 0.20
