### ISSUE TITLE
Segmentation fault in release compile

### ISSUE THREAD

**Issue by Geemili** [gyscos/Cursive#86]
**Issue**

Starting a cursive application using the `pancurses` backend when compiled with `cargo build --release` causes a segmentation fault. The program starts, shows a window, but then crashes with a segmentation fault.

**Setup**

```
cargo 0.13.0-nightly (806e3c3 2016-10-26)
rustc 1.14.0-nightly (3f4408347 2016-10-27)
```

```toml
[dependencies.cursive]
version = "0.3"
default-features = false
features = ["pancurses"]
```

* * *

I don't have a code snippet to show this behavior, but I hope to make one during the weekend.
